//HintName: GeneratedHelloWorld.g.cs
// <auto-generated/>
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;

namespace Generated;

/// <summary>
/// Auto-generated class containing HelloWorld functionality and type introspection
/// </summary>
public static class GeneratedHelloWorld
{
    /// <summary>
    /// Returns the classic Hello World greeting
    /// </summary>
    /// <returns>Hello, World!</returns>
    public static string SayHello()
    {
        return "Hello, World!";
    }

    /// <summary>
    /// Returns information about available types and methods in the compilation context
    /// </summary>
    /// <returns>A formatted string containing type and method information</returns>
    public static string GetAvailableTypesAndMethods()
    {
        return @"=== Compilation Context Information ===
Assembly: TestAssembly
Language: C#

=== Available Types (first 10) ===
Type: TestNamespace.GenericClass<T>
  Method: ProcessItem(T)

Type: TestNamespace.ConstrainedGeneric<T>
  Method: CreateNew()

Type: TestNamespace.IGenericInterface<TInput, TOutput>
  Method: Process(TInput)

Type: FxResources.System.Console.SR
  (No public methods)

Type: System.Console
  Method: ReadKey()
  Method: ReadKey(Boolean)
  Method: ResetColor()

Type: System.ConsoleCancelEventHandler
  Method: Invoke(Object, ConsoleCancelEventArgs)
  Method: BeginInvoke(Object, ConsoleCancelEventArgs, AsyncCallback, Object)
  Method: EndInvoke(IAsyncResult)

Type: System.ConsoleCancelEventArgs
  (No public methods)

Type: System.ConsoleColor
  (No public methods)

Type: System.ConsoleSpecialKey
  (No public methods)

Type: System.ConsoleKey
  (No public methods)

";
    }

    /// <summary>
    /// Returns a list of all available type names
    /// </summary>
    /// <returns>Array of type names</returns>
    public static string[] GetTypeNames()
    {
        return new string[]
        {
            "TestNamespace.GenericClass<T>",
            "TestNamespace.ConstrainedGeneric<T>",
            "TestNamespace.IGenericInterface<TInput, TOutput>",
            "FxResources.System.Console.SR",
            "System.Console",
            "System.ConsoleCancelEventHandler",
            "System.ConsoleCancelEventArgs",
            "System.ConsoleColor",
            "System.ConsoleSpecialKey",
            "System.ConsoleKey",
            "System.ConsoleKeyInfo",
            "System.ConsoleModifiers",
            "System.ConsolePal",
            "System.SR",
            "System.SR",
            "System.__Canon",
            "System.ArgIterator",
            "System.Array",
            "System.SZArrayHelper",
            "System.Attribute"
        };
    }
}